services:
  spring-boot-api:
    build:
      context: .
      dockerfile: Dockerfile.spring-boot
    image: spring-boot-api:latest
    container_name: spring-boot-api
    ports:
      - "8080:8080"
    depends_on:
      - redis-cache

  redis-cache:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "5432:5432"
    volumes:
      - redis-cache:/data

  nginx-server:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: nginx-server:latest
    container_name: nginx-server
    ports:
      - "80:80"
    depends_on:
      - spring-boot-api

volumes:
  redis-cache:

