services:
  spring-boot-api:
    build:
      context: .
      dockerfile: Dockerfile.spring-boot
    image: spring-boot-api:latest
    container_name: spring-boot-api
    env_file:
      - .env
    ports:
      - "8080:8080"

  pgvector:
    image: pgvector/pgvector:pg16
    container_name: pgvector
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vector_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgvector-data:/var/lib/postgresql/data

  nginx-server:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-files/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-files/sites-available:/etc/nginx/sites-available
      - ./nginx-files/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx-files/certs:/etc/letsencrypt/live/nycweather.me
      - ./nginx-files/sites-available/default.conf:/etc/nginx/conf.d/default.conf
    command: >
      /bin/sh -c "ln -sf /etc/nginx/sites-available/nycweather.me.conf /etc/nginx/sites-enabled/nycweather.me.conf &&
      ln -sf /etc/nginx/sites-available/default.conf /etc/nginx/sites-enabled/default.conf &&
      nginx -g 'daemon off;'"
