name: demo

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  greeting:
    runs-on: debian-latest
    steps:
      - name: Greeting
        run: echo "Hello, world!"