name: Deploy v2

on:
  push:
    branches: [ create-actions ]

jobs:
  setup-build-publish-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: 'See active compute instances'
        run: 'gcloud compute instances list'

      - name: Prepare SSH keys for gcloud
        run: |
          mkdir -p /home/runner/.ssh
          ssh-keygen -t rsa -b 2048 -f /home/runner/.ssh/google_compute_engine -q -N ""
          gcloud compute os-login ssh-keys add --key-file=/home/runner/.ssh/google_compute_engine.pub