name: Deploy to GCE

on:
  pull_request:
    branches: [ main, create-actions ]

jobs:
  setup-build-publish-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Set up JDK 17'
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: 'Build with Maven'
        run: mvn clean install -DskipTests

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: 'Get GitHub runner IP address'
        id: runner_ip
        run: echo "RUNNER_IP=$(curl -s https://checkip.amazonaws.com)" >> $GITHUB_ENV

      - name: 'Allow SSH from GitHub runner IP'
        run: |
          gcloud compute firewall-rules create allow-ssh-from-github-runner \
            --direction=INGRESS \
            --priority=1000 \
            --network=vpc-network \
            --action=ALLOW \
            --rules=tcp:22 \
            --source-ranges=${{ env.RUNNER_IP }}

      - name: 'Generate SSH key'
        run: |
          gcloud compute ssh ${{ secrets.GCP_SA_NAME }}@${{ secrets.GCP_COMPUTE_INSTANCE_NAME }} --zone ${{ secrets.GCP_ZONE }} --command "echo SSH key generated"

      - name: Copy files to GCE instance
        run: gcloud compute scp target/*.jar ${{ secrets.GCP_SA_NAME }}@${{ secrets.GCP_COMPUTE_INSTANCE_NAME }}:~/app.jar --zone ${{ secrets.GCP_ZONE }}

      - name: 'Remove SSH access from GitHub runner IP'
        if: always()
        run: |
          gcloud compute firewall-rules delete allow-ssh-from-github-runner -q
