name: Deploy to google compute engine

on:
  push:
    branches: [ main ]

jobs:
  setup-build-publish-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install package -DskipTests

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Transfer jar to Compute Engine
        run: gcloud compute scp ./target/peppermint.jar spring-boot-instance:/path/to/destination --zone us-east1-b

      - name: SSH and Execute jar on VM
        run: |
          gcloud compute ssh spring-boot-instance --zone us-east1-b --command="nohup java -jar /path/to/destination/peppermint.jar &"