name: Deploy v2

on:
  push:
    branches: [ create-actions ]

jobs:
  setup-build-publish-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: 'See active compute instances'
        run: 'gcloud compute instances list'

      - name: Create demo test file
        run: echo "This is a demo test file." > demo_test.txt

      - name: Generate SSH key
        run: |
          gcloud compute ssh github-actions-service-account@spring-boot-instance --zone us-east1-b --command "echo SSH key generated"

      - name: Wait for SSH key propagation
        run: sleep 60

      - name: Transfer demo test file to Compute Engine
        run: gcloud compute scp ./demo_test.txt github-actions-service-account@spring-boot-instance:/home/github-actions-service-account/code --zone us-east1-b
