name: Deploy to Google Compute Engine

on:
  push:
    branches: [ main ]

jobs:
  setup-build-publish-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install package -DskipTests

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate GCP account
        run: gcloud auth list

      - name: Verify GCP Authentication
        run: |
          if gcloud auth list | grep -q 'No credentialed accounts.'; then
            echo "Authentication failed."
            exit 1
          else
            echo "Authentication successful."
          fi
